name: Add issues and PRs to the Dedalo project

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  add-to-project:
    name: Add to project
    runs-on: ubuntu-latest
    steps:
      - name: Generate JWT for GitHub App
        id: generate-jwt
        run: |
          echo "Generating JWT..."
          jwt=$(ruby -r openssl -r base64 -r json -e "payload = { iat: Time.now.to_i, exp: Time.now.to_i + 600, iss: ${{ secrets.APOLLO_APP_ID }} }; key = OpenSSL::PKey::RSA.new(File.read('${{ secrets.APOLLO_APP_SECRET }}')); token = Base64.urlsafe_encode64(JSON.generate(payload).force_encoding('ASCII-8BIT')).tr('=', '') + '.' + Base64.urlsafe_encode64(key.sign(OpenSSL::Digest::SHA256.new, JSON.generate(payload)).force_encoding('ASCII-8BIT')).tr('=', ''); puts token")
          echo "jwt=${jwt}" >> $GITHUB_ENV

      - name: Get installation access token
        id: get-installation-token
        run: |
          installation_id=$(curl -s -X GET \
            -H "Authorization: Bearer ${{ env.jwt }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/app/installations | jq '.[0].id')
          access_token=$(curl -s -X POST \
            -H "Authorization: Bearer ${{ env.jwt }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/app/installations/$installation_id/access_tokens | jq -r .token)
          echo "access_token=${access_token}" >> $GITHUB_ENV

      - uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/orgs/eduNEXT/projects/1
          github-token: ${{ env.access_token }}
